Repository Fripouney/Ney-Editor, pull requests merged in 2025-08, with the labels that each got.

#29 [ISSUE #27] Added feature to color text
  file_handling.py
  ney.py
Labels: Feature

#30 Open file from argument command line
  file_handling.py
  ney.py
Labels: Enhancements

#31 [ISSUE #28] Big refactoring
  README.md
  config.py
  file_handling.py
  ney.py
  service/error_handler.py
  service/file_opener.py
  test/config_test.py
  test/ney_test.py
  test/utils_test.py
  utils.py
Labels: Refactor

#32 [ISSUES #23 #25] Text size & multiple formats at once
  README.md
  config.py
  ney.py
  service/file_opener.py
  service/text_formatter.py
  test/config_test.py
  test/service/text_formatter_test.py
Labels: Feature, Enhancements
